version: '3'

services:
  # Laravel application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
    volumes:
      - .:/var/www/html
    environment:
      # Adjust DATABASE_* environment variables according to your existing database configuration
      - APP_ENV=local
      - APP_DEBUG=true
      - DATABASE_HOST=47.129.17.36
      - DATABASE_PORT=3306
      - DATABASE_DATABASE=attendance_test1
      - DATABASE_USERNAME=vitou_wct
      - DATABASE_PASSWORD=vitou2357.!
