version: "26"
services:

    # PHP Service
    php:
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=local
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 8100:8100
        depends_on:
            - redis

    # Redis Server
    redis:
        image: redis:alpine
        command: redis-server --appendonly yes --requirepass  "${REDIS_PASSWORD}"
        ports:
            - 6379:6379
        environment:
            - REDIS_PASSWORD=vitou2357.!


volumes:
    db-data: ~