FROM ubuntu:latest

WORKDIR /laravel_project

# Install dependencies
RUN apt -y update 
RUN apt -y upgrade
RUN apt install -y zip unzip git curl

# install php
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get install ca-certificates apt-transport-https software-properties-common -y
RUN add-apt-repository ppa:ondrej/php
RUN apt update
# RUN apt-get install -y tzdata
RUN apt-get install -y php

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Copy existing application directory contents
COPY . ./laravel_project

RUN rm -r vendor

# composer install
RUN composer update --no-scripts

# Generate Laravel application key
RUN php artisan key:generate

# Expose port (if needed)
EXPOSE 81

# CMD or ENTRYPOINT instructions here if needed
CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=81"]
